var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                         >                 %                                    ",
   "                                         yyyyy	                                ",
   "                                          o o                                   ",
   "                                 o o                                            ",
   "                         o o    xxxx            o     o                         ",
   "                   o o  xxxx            v                o o                    ",
   "  x          o o  xxxxx     xx     xx   xxxxxxxx       xxxxxx  o              x ",
   "  x  @      xxxxx             x!!!x                           xxx        *    x ",
   "  x                           x!!!x               !!!!             xxx        x ",
   "  xxxxxxxxx                   xxxxx              xxxxxx               xxxxxxxxx ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                              					  ",
   "                                                                                                         x        ",
   "                                                                                                         x        ",
   "                                                             ||                                    *     x        ",
   "                                                                                                         x        ",
   "                                                                                                xxxxxxxxxx        ",
   "                                                                                                x                 ",
   "                                                                              yyyyyy      o o   x                 ",
   "                                                                                       xxxxxxxxxx                 ",
   "                                                                                       xxx                        ",
   "                                                                                o      xxx                        ",
   "                                                             =           x    xxxxx    xxx                        ",
   "                                                                          xx          xx                          ",
   "                >                                                 o o       xx!!!!!!xx                            ",
   "                               yyyyyyy                    xo   x               xxxx                               ",
   "                                                          xx   x                                                  ",
   "                                                          x   ox                                                  ",
   "                                                              xx xxxxxxxx                                         ",
   "                                     %                         x  												  ",
   "     @        o o o                                 o o o o    x  												  ",
   "             xxxxxxxx                             xxxxxxxxxxxxxx  												  ",
   "    xxx      x          o o o                     x															      ",
   "    x x      x        xxxxxxxx                    x																  ",
   "!!!!x x!!!!!!x                     =       o o o  x																  ",
   "!!!!x x!!!!!!x                           xxxxxxxxxx 															  ",
   "!!!!x x!!!!!!x                               																	  ",
   "!!!!x x!!!!!!x                               																	  ",
   "!!!!x x!!!!!!x             v    o o o     v                                    									  ",
   "!!!!x x!!!!!!x    x!!!!!!!!!!!xxxxxxxxx!!!!!!!xx                    x!!!!!!!!!!!!!!x                              ",
   "!!!!x x!!!!!!x      x!!!!!!!!!!!!!!!!!!!!!!!!!xx                    x!!!!!!!!!!!!!!x                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                           x  ",
   "                                                                                                        *  x  ",
   "                                                                                                           x  ",
   "                                                                                                   o   xxxxx  ",
   "                                                                                                 xxxxx        ",
   "                                                                                                              ",
   "                                                                                              o               ",
   "                                                                                            xxxxx             ",
   "                                                                                        o                     ",
   "                             =                                                        xxxxxx                  ",
   "                                                                                                              ",
   "                                               =                 yyyyyyyyy                                    ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                 o o            o o                           ",
   "                                                                xxxxxx        xxxxxxx                         ",
   "                                                   %                                                          ",
   "                                          xxxx    xxx x                                                       ",
   "                                        xx o       o   xx                                                     ",
   "                                                      xx               x!!!!!x                                ",
   "                                         xx            xx               xxxxx                                 ",
   "                     >                      xxx        xx                                                     ",
   "                                                     xx                                                       ",
   "                                                   xxx                                                        ",
   "                                                 x x                                                          ",
   "                                  o o o     xx  x                                                             ",
   "  x                            xxxxxxxxxxx                                                                    ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x              o o o                                                                                        ",
   "  x       @     xxxxxxxx                                                                                      ",
   "  x                                                                                                           ",
   "  x     xxxxxxxx                                                                                              ",
   "  x                        x                x                     x                x                          ",
   "  x                        x||   v      v ||x                     x||   v      v ||x                          ",
   "  x   =     =              x!!!!!!!!!!!!!!!!x    =         =      x!!!!!!!!!!!!!!!!x                          ",
   "  x                        x!!!!!!!!!!!!!!!!x                     x!!!!!!!!!!!!!!!!x                          ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                           x     !x  o  x     ",
   "                                                                                           x     !x  o  x     ",
   "                                                                                           xx    !x  o  x     ",
   "                                                                                                x!x  o  x     ",
   "                                                                       =                       x !x  o  x     ",
   "                                                                                                 !x  o  x     ",
   "                                                                                            xxx  !x  o  x     ",
   "                               =                                                                 !x  o  x     ",
   "                                                        >                              xxx       !x  o  x     ",
   "                                                                                                 !x  o  x     ",
   "                                                                                    xx           !x  o  x     ",
   "                                                                                                 !x  o  x     ",
   "                                                                                xx               !x  o  x     ",
   "                                                                                                 !x  o  x     ",
   "                      %                                          xxxxxxxx                        !x  o  x     ",
   "                    xxxxxx                                                                       !x  o  x     ",
   "                              v                    xxxxxxxx                                      !x  o  x     ",
   "                                                                           v                     !x  o  x     ",
   "                                                  v                                              !x  o  x     ",
   "                                       xxxxx                                                     !x  o  x     ",
   "                                                                                                 !x  o  x     ",
   "                           xxxxx        v                         v                    v         !x  o  x     ",
   "                                                                                                  x  o  x     ",
   "                 xxxxxxxxx    |                        |                       |                 |x  o  x     ",
   "                xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  o  x     ",
   "            x  xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  o  x     ",
   "     @      xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  o     *  ",
   "            xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  o        ",
   " xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx "]
  ["                                                                                       ",
   "                                                                                       ",
   "	x     x   o o o o  x      x       x                  x    **     x       x    xx   ",                  
   "	x     x   o     o  x      x        x                x     **     x x     x    xx   ",                   
   "	x     x   o     o  x      x         x      x       x      **     x  x    x    xx   ",                  
   "	 x    x   o     o  x      x          x    x  x    x       **     x   x   x    xx   ",                   
   "	   xx     o     o  x      x           x  x    x  x        **     x    x  x    xx   ",                    
   "		x     o     o  x      x            x        x         **     x     x x    xx   ",             
   "		x     o     o  x      x            x        x         **     x      xx    xx   ",             
   "		x     o o o o   x xx x             x        x         **     x       x    xx   "]   
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
